### PR TITLE
Updated Chrome/ChromeDriver to latest stable

### PR DESCRIPTION
**Pull request by flxtcha**

### CODE REVIEW

**Comment by markhobson** [comment]
Thanks, but the images fail to build as the Chrome version can't be found. See the README for build and upgrade instructions.

**Comment by markhobson** [comment]
There are also several tasks that follow on from this - see https://github.com/markhobson/docker-maven-chrome/issues/57#issuecomment-2327418070.

**Comment by flxtcha** [comment]
> There are also several tasks that follow on from this - see [#57 (comment)](https://github.com/markhobson/docker-maven-chrome/issues/57#issuecomment-2327418070).

I've covered these please review the latest commit. The tests were failing due to DuckDuckGo bot detection (see screenshot) 
screenshot

**Comment by markhobson** [comment]
Thanks for looking into the failing test. Although it is still failing for me here:

```
   [ERROR] Errors: 
   [ERROR]   BrowserTest.canDuck:67 » NoSuchElement no such element: Unable to locate element: {"method":"css selector","selector":".anomaly\-modal__title"}
     (Session info: chrome=128.0.6613.119)
   For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
   Build info: version: '4.24.0', revision: '748ffc9bc3'
   System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-40-generic', java.version: '11.0.23'
   Driver info: org.openqa.selenium.chrome.ChromeDriver
   Command: [13f65c883082fb061f198f98010ad3ab, findElement {value=anomaly-modal__title, using=class name}]
   Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.119, chrome: {chromedriverVersion: 128.0.6613.119 (6e439cfca4d..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:43279}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:43279/devtoo..., se:cdpVersion: 128.0.6613.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
   Session ID: 13f65c883082fb061f198f98010ad3ab
```

I wasn't aware that they've added bot detection. It's not great to be asserting on that, so really need to find a more suitable website for testing.

**Comment by Jobvdb** [comment]
We are depending on this PR. Any status update?

**Comment by markhobson** [comment]
@Jobvdb I've done some work on this locally and hope to push it back soon. I'm limited by my spare time I'm afraid.

**Comment by markhobson** [comment]
Upgraded Chrome and ChromeDriver to 130.0.6723.58.

Had to drop Java 8 support since Selenium 4.14.0 requires Java 11. Also updated demo/test projects to use a standalone server to isolate them from external website changes such as DuckDuckGo.

**Pull request closed without merging**
